# Generated by Django 4.2 on 2024-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
