# Generated by Django 4.2 on 2024-06-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_membership_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
    ]
