# Generated by Django 4.2 on 2024-06-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_course_created_at_course_updated_at_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
