# Generated by Django 4.2 on 2024-06-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.company'),
        ),
    ]
