# Generated by Django 4.2 on 2024-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
