# Generated by Django 4.2 on 2024-06-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_subscribed',
        ),
    ]
