# Generated by Django 4.2 on 2024-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_subscription_date_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
