# Generated by Django 4.2 on 2024-06-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_subscription_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
