# Generated by Django 4.2 on 2024-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_subscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='courses',
            field=models.ManyToManyField(through='members.Subscription', to='members.course'),
        ),
    ]
