# Generated by Django 4.2 on 2024-06-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_member_user_alter_subscription_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
